language:  generic

notifications:
  slack:
    rooms:
      - apacheexpress:9z2IfvxZfENp0TFmiYCgyUKz

matrix:
    include:
# this fails, no log, no idea.
#        - os:   osx
#          osx_image: xcode8.3
        - os:   osx
          osx_image: xcode9
        - os:   osx
          osx_image: xcode9.2
        - os:   osx
          osx_image: xcode9.3beta

before_install:
    - brew update # otherwise we fail the Xcode9 image

script:
    - brew tap swiftxcode/swiftxcode
    - brew install swift-xcode
